In [1]:
import pandas as pd
import numpy as np

In [4]:
file_name = input('Enter the file name please :')
file_ext = input('Enter the file extension please :')

Enter the file name please : XboxOne_GameSales.csv
Enter the file extension please : csv

READING THE IMPORTED DATA

In [11]:
 
def DataReading(file_name, file_ext):
    if file_ext == 'csv':
        df = pd.read_csv(file_name, encoding='latin-1')
    elif file_ext == 'excel':
        df = pd.read_excel(file_name, encoding='latin-1')
    elif file_ext == 'json':
        sf = pd.read_json(file_name ,encoding='latin-1')
    else:
        raise ValueError("file not acceptable")

    return df

In [12]:
df = DataReading(file_name, file_ext)

SUMMARIZING THE DATA

In [16]:
df.shape

(613, 10)

In [17]:
df.describe()

,Pos,Year,North America,Europe,Japan,Rest of World,Global
count,613.000000,505.000000,613.000000,613.000000,613.000000,613.000000,613.000000
mean,307.000000,2015.821782,0.265628,0.132447,0.000832,0.039951,0.438874
std,177.102136,1.382975,0.594940,0.335311,0.004216,0.089343,0.983147
min,1.000000,2013.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,154.000000,2015.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,307.000000,2016.000000,0.050000,0.000000,0.000000,0.010000,0.060000
75%,460.000000,2017.000000,0.240000,0.100000,0.000000,0.030000,0.380000
max,613.000000,2020.000000,4.700000,3.250000,0.040000,0.760000,8.720000

In [18]:
df.drop_duplicates()

,Pos,Game,Year,Genre,Publisher,North America,Europe,Japan,Rest of World,Global
0,1,Grand Theft Auto V,2014.0,Action,Rockstar Games,4.70,3.25,0.01,0.76,8.72
1,2,Call of Duty: Black Ops 3,2015.0,Shooter,Activision,4.63,2.04,0.02,0.68,7.37
2,3,Call of Duty: WWII,2017.0,Shooter,Activision,3.75,1.91,0.00,0.57,6.23
3,4,Red Dead Redemption 2,2018.0,Action-Adventure,Rockstar Games,3.76,1.47,0.00,0.54,5.77
4,5,MineCraft,2014.0,Misc,Microsoft Studios,3.23,1.71,0.00,0.49,5.43
...,...,...,...,...,...,...,...,...,...,...
608,609,Biomutant,2018.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
609,610,Biomutant,2019.0,Action,THQ Nordic,0.00,0.00,0.00,0.00,0.00
610,611,de Blob,2017.0,Platform,THQ Nordic,0.00,0.00,0.00,0.00,0.00
611,612,Outcast: Second Contact,2017.0,Adventure,Bigben Interactive,0.00,0.00,0.00,0.00,0.00
612,613,Code Vein,2019.0,Action,Bandai Namco Entertainment,0.00,0.00,0.00,0.00,0.00

In [20]:
df['Genre'].value_counts()

Genre
Action              147
Shooter              70
Sports               60
Misc                 49
Racing               47
Adventure            47
Role-Playing         45
Platform             32
Action-Adventure     31
Simulation           21
Strategy             18
Fighting             17
Music                14
Puzzle               11
MMO                   2
Visual Novel          2
Name: count, dtype: int64

HANDLING MISSING VALUES

In [27]:
def HandlingMissingValues(df, command ='remove'):
    if command == 'remove':
        df = df.dropna()
    elif command == 'impute':  # Use 'elif' instead of 'else' for multiple conditions
        df = df.fillna(df.mean())  # Fill null values with mean

    return df

In [30]:
df = HandlingMissingValues(df, command = 'remove' )

 CATEGORICAL DATA ENCODING

In [33]:
def DataEncoding(df):
    encoded_df = pd.get_dummies(df)
    return encoded_df

In [34]:
e_df = DataEncoding(df)

In [35]:
e_df

,Pos,Year,North America,Europe,Japan,Rest of World,Global,Game_7 Days to Die,Game_A Way Out,Game_ABZU,...,Publisher_Tripwire Interactive,Publisher_Tru Blu Entertainment,Publisher_UIG Entertainment,Publisher_Ubisoft,Publisher_Unknown,Publisher_Versus Evil,Publisher_Warner Bros. Interactive Entertainment,Publisher_Wired Productions,Publisher_Wizards of the Coast,Publisher_Yacht Club Games
0,1,2014.0,4.70,3.25,0.01,0.76,8.72,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,2,2015.0,4.63,2.04,0.02,0.68,7.37,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,3,2017.0,3.75,1.91,0.00,0.57,6.23,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,4,2018.0,3.76,1.47,0.00,0.54,5.77,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,5,2014.0,3.23,1.71,0.00,0.49,5.43,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
608,609,2018.0,0.00,0.00,0.00,0.00,0.00,False,False,False,...,False,False,False,False,False,False,False,False,False,False
609,610,2019.0,0.00,0.00,0.00,0.00,0.00,False,False,False,...,False,False,False,False,False,False,False,False,False,False
610,611,2017.0,0.00,0.00,0.00,0.00,0.00,False,False,False,...,False,False,False,False,False,False,False,False,False,False
611,612,2017.0,0.00,0.00,0.00,0.00,0.00,False,False,False,...,False,False,False,False,False,False,False,False,False,False
612,613,2019.0,0.00,0.00,0.00,0.00,0.00,False,False,False,...,False,False,False,False,False,False,False,False,False,False